version: '3.3'
services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  reddit_comment_api:
    image: ghcr.io/adadkins/reddit_comment_api:latest
    restart: always
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB_NAME=postgres
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reddit_comment_api.rule=Host(`redditapi.adadkins.com`)"
      - "traefik.http.routers.reddit_comment_api.entrypoints=web"
  shorturl:
    image: ghcr.io/adadkins/url_shortener:latest
    restart: always
    environment:
      - hostname=shorturl.adadkins.com
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB_NAME=postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shorturl.rule=Host(`shorturl.adadkins.com`)"
      - "traefik.http.routers.shorturl.entrypoints=web"
    depends_on:
      - db
  reddit_comment_puller:
    image: ghcr.io/adadkins/reddit_comment_puller:latest
    restart: always
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB_NAME=postgres
    depends_on:
      - db

volumes:
  db:
    driver: local
