version: '2'
services:
  plex:
    container_name: plex
    image: linuxserver/plex:arm32v7-1.32.4
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=claim-TiBSNx_h9bXphrpCrTrd
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    network_mode: host
    volumes:
      - /media/pi/plex/config:/config
      - /media/pi/plex/temp:/transcode
      - /media/pi/plex:/data
