version: "3.7"
services:
  plex:
    container_name: plex
    image: linuxserver/plex:amd64-1.27.2
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=PLEX_CLAIM_HASH
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    network_mode: bridge
    ports:
      - "32400:32400" # (for access to the Plex Media Server) [required]
      - "3005:3005" # (for controlling Plex Home Theater via Plex Companion)
      - "8324:8324" # (for controlling Plex for Roku via Plex Companion)
      - "32410:32410/udp" # (for current GDM network discovery)
      - "32412:32412/udp" # (for current GDM network discovery)
      - "32413:32413/udp" # (for current GDM network discovery)
      - "32414:32414/udp" # (for current GDM network discovery)
      - "32469:32469" # (for access to the Plex DLNA Server)
    volumes:
      - /Volumes/Partition2TB/config:/config
      - /Volumes/Partition2TB/transcode:/transcode
      - /Volumes/Partition2TB:/data
