version: '3.3'
services:
    transmission-openvpn:
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        volumes:
            - '/media/pi/transmission:/data'
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - NORDVPN_COUNTRY=CA
            - NORDVPN_CATEGORY=legacy_p2p
            - NORDVPN_PROTOCOL=tcp
            - OPENVPN_USERNAME=SERVICE_USERNAME
            - OPENVPN_PASSWORD=SERVICE_PASSWORD
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
